### ISSUE TITLE
Support namespace in project name

### ISSUE THREAD

**Issue by jwerle** [zetzit/zz#56]
I can see much benefit from allowing one to do:

```toml
[project]
name = "namespace::library"
```

allowing:

```c++
using namespace::library::{ some_export }
```

ZZ currently complains that it can't find the module 'namespace::library' because of the `::` contained in the name.

@aep what are your thoughts on support something like this? I hope this makes sense
